version: '3.7'
services:
  db:
    image: mysql:8
    restart: always
    env_file:
      - environments/.env
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    # Where our data will be persisted
    volumes:
      - ./my-db_5:/var/lib/mysql
      - ./mytap:/mytap
      - ./tests:/mysql_tests
